import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopBanner from "./components/layouts/banner/TopBanner";
import Navbar from "./components/layouts/navbar/navbar";
import Footer from "./components/layouts/Footer/page";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <TopBanner />
        <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  );
}
