import type { Metadata } from "next";
import "./globals.css";
import TopBanner from "./components/layouts/banner/TopBanner";
import Navbar from "./components/layouts/navbar/navbar";
import Footer from "./components/layouts/Footer/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <TopBanner />
        <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  );
}
